/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVideoRouteImport } from './routes/app.video'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppImageRouteImport } from './routes/app.image'
import { Route as AppEditRouteImport } from './routes/app.edit'
import { Route as AppDesignRouteImport } from './routes/app.design'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVideoRoute = AppVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppImageRoute = AppImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => AppRoute,
} as any)
const AppEditRoute = AppEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignRoute = AppDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/app/chat': typeof AppChatRoute
  '/app/design': typeof AppDesignRoute
  '/app/edit': typeof AppEditRoute
  '/app/image': typeof AppImageRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/video': typeof AppVideoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/app/chat': typeof AppChatRoute
  '/app/design': typeof AppDesignRoute
  '/app/edit': typeof AppEditRoute
  '/app/image': typeof AppImageRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/video': typeof AppVideoRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/app/chat': typeof AppChatRoute
  '/app/design': typeof AppDesignRoute
  '/app/edit': typeof AppEditRoute
  '/app/image': typeof AppImageRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/video': typeof AppVideoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/chat'
    | '/api/generate-image'
    | '/app/chat'
    | '/app/design'
    | '/app/edit'
    | '/app/image'
    | '/app/templates'
    | '/app/video'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/generate-image'
    | '/app/chat'
    | '/app/design'
    | '/app/edit'
    | '/app/image'
    | '/app/templates'
    | '/app/video'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/chat'
    | '/api/generate-image'
    | '/app/chat'
    | '/app/design'
    | '/app/edit'
    | '/app/image'
    | '/app/templates'
    | '/app/video'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/video': {
      id: '/app/video'
      path: '/video'
      fullPath: '/app/video'
      preLoaderRoute: typeof AppVideoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/image': {
      id: '/app/image'
      path: '/image'
      fullPath: '/app/image'
      preLoaderRoute: typeof AppImageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/edit': {
      id: '/app/edit'
      path: '/edit'
      fullPath: '/app/edit'
      preLoaderRoute: typeof AppEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/design': {
      id: '/app/design'
      path: '/design'
      fullPath: '/app/design'
      preLoaderRoute: typeof AppDesignRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDesignRoute: typeof AppDesignRoute
  AppEditRoute: typeof AppEditRoute
  AppImageRoute: typeof AppImageRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppVideoRoute: typeof AppVideoRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDesignRoute: AppDesignRoute,
  AppEditRoute: AppEditRoute,
  AppImageRoute: AppImageRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppVideoRoute: AppVideoRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
